; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DataBaseDictionary"
#define MyAppVersion "0.1"
#define MyAppPublisher "Cristian Solervicéns"
#define MyAppURL "https://github.com/CristianSolervicens/DataBaseDictionary.Net"
#define MyAppExeName "DataBaseDictionary.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{32042862-5BC5-46B3-AC29-1896EA751C74}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=DataBaseDictionary
SetupIconFile=C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\_Frog Full.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\FrogFull.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\DataBaseDictionary.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\DataBaseDictionary.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\DataBaseDictionary.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\DataBaseDictionary.staticwebassets.runtime.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\ModelLibrary.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\ModelLibrary.staticwebassets.runtime.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\Razor.Templating.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\System.Data.SqlClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MisArchivos\dev\C#\DataBaseDictionary.Net\DataBaseDictionary\bin\Release\net8.0-windows\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

